CDN_PURE:='https://cdn.jsdelivr.net/npm/purecss@3.0.0/build'

pure: pure-min.css grids-responsive-min.css

pure-min.css:
	curl ${CDN_PURE}/$@ -o $@

grids-responsive-min.css:
	curl ${CDN_PURE}/$@ -o $@
